spring:
  application:
    name: survey-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: S@ndhy@1
    url: jdbc:mysql://localhost:3306/survey_service
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9000